name: flutter_read
description: Flutter小说阅读器
version: 1.0.1
homepage: https://github.com/ysbing/flutter_read

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  synchronized: ^3.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
